### ISSUE TITLE
Proposal of a goal clarification for this crate

### ISSUE THREAD

**Issue by prhod** [CanalTP/osm-transit-extractor#36]
This crate was initiated to read an OSM PBF file and extract PT informations (mainly buses for the moment). 
As stated in https://github.com/CanalTP/osm-transit-extractor/issues/27 the problem is `stop_positions` and `platforms` are then undistinguishable, and thus causes trouble when using output data.

## Actual mapping
The actual mapping is : 

osm object | crate object
--- | ---
route_master | Line
route | Route
stop_position | StopPoint
platform | StopPoint
stop_area | StopArea

## Proposal
Focus this crate as an OSM extract system with as less transformation as possible, but some changes in properties' name to ease usability : 
* rename StopPoint as StopPosition for stop_position
* rename StopPoint as Platform for stop_position

Routes will be modified accordingly : 
* ordered_stops_id will be renamed as ordered_platforms_id
* a new list ordered_stop_positions_id will be added

Those changes will also imply changing CSV outputs.

**Comment by nlehuby** [comment]
+1 to clarify the goal and put it in the readme.

Ok to focus on extraction and not on transformation (at least for now).

But I'm not sure about the object mapping:
I think it is pretty cool that we simplify the OSM notions for our users. For instance, some of the OSM keys on relations are quite strange, and are easier to understand in this crate:
* `destination` instead of `to` :+1:
* `mode` instead of `route` or `route_master` :+1:

And `type=route_master` is one of them: the meaning of the `route_master` word is not clear, whereas `line` is.

**Comment by prhod** [comment]
thanks for the feedback, I've changed the proposal accordingly. I've added changes in the Route object. are you ok with the proposal ?

**Comment by nlehuby** [comment]
:+1:

**Comment by nlehuby** [comment]
BTW, the process and the logic to define the `StopPosition` and `Platform` should be documented so the data users do not have to read the code to understand.
We may create a metadata file following [the W3C standard](https://www.w3.org/TR/tabular-data-primer/#metadata) or use [the taginfo file](https://github.com/CanalTP/osm-transit-extractor/blob/master/taginfo.json) we already have.

**Comment by prhod** [comment]
fixed by https://github.com/CanalTP/osm-transit-extractor/pull/37
